from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Text, DateTime, JSON
from backend.database.connection import Base

class AIGPAllocationRecord(Base):
    """
    KrushiSetu Central AI/ML Engine: Panchayat Samiti -> Gram Panchayat Crop Allocation Record.
    
    DUAL-STORAGE INTEGRITY GUARANTEE:
    - ai_recommended_quantity_mt, ai_priority, and ai_confidence_score are generated by the Central AI
      and preserved permanently as an immutable historical record.
    - When a Panchayat Samiti Officer reviews and approves/corrects an allocation, the decision is stored
      in human_final_quantity_mt, human_final_priority, reviewed_by, and reviewed_at.
    - Any human modification requires a mandatory operational correction_reason (>= 5 chars).
    - The original AI calculation is NEVER overwritten or altered.
    """
    __tablename__ = "ai_gp_allocation_records"

    id = Column(Integer, primary_key=True, index=True)
    allocation_code = Column(String(50), unique=True, index=True, nullable=False) # e.g. GPA-2026-0001
    batch_code = Column(String(50), index=True, nullable=False) # Groups all GPs for a given FD requirement (e.g. BATCH-GPA-2026-001)
    fd_requirement_id = Column(Integer, nullable=True, index=True) # Reference to FDCropRequirement or FDPSAllocation

    # Jurisdictional Identification
    panchayat_samiti_name = Column(String(100), nullable=False, index=True) # e.g. Baramati Block Panchayat Samiti
    gp_code = Column(String(50), nullable=False, index=True) # e.g. GP-BMT-01
    gp_name = Column(String(100), nullable=False, index=True) # e.g. Shirsuphal Gram Panchayat
    
    # Agricultural Context
    crop_name = Column(String(100), nullable=False, index=True)
    season = Column(String(50), nullable=False)
    target_year = Column(Integer, default=2026)
    agricultural_area_ha = Column(Float, nullable=True) # Cultivable area in hectares
    active_farmers_count = Column(Integer, default=0)

    # 1. Central AI Recommendation Values (IMMUTABLE - Never Overwritten)
    ai_recommended_quantity_mt = Column(Float, nullable=False)
    ai_priority = Column(String(50), nullable=False, default="HIGH") # NORMAL, HIGH, CRITICAL
    ai_suitability = Column(String(50), default="HIGH_SUITABILITY") # HIGH_SUITABILITY, MEDIUM_SUITABILITY, MODERATE_SUITABILITY
    ai_reasoning = Column(Text, nullable=True)
    ai_confidence_score = Column(Float, default=0.94)
    model_name = Column(String(100), default="Central AI - PSToGPAllocationModel")
    model_version = Column(String(50), default="v1.0.0-prototype")
    
    # JSON factors used by AI (soil_type, irrigation_pct, organic_matter, share_pct, etc.)
    ai_factors = Column(JSON, nullable=True)

    # 2. Human Final Review & Decision Values (Dual-Storage Override)
    review_status = Column(String(50), default="PENDING_REVIEW", index=True) # PENDING_REVIEW, APPROVED, CORRECTED
    human_final_quantity_mt = Column(Float, nullable=True)
    human_final_priority = Column(String(50), nullable=True)
    reviewed_by = Column(String(100), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    correction_reason = Column(Text, nullable=True) # Mandatory if modified from AI recommendation
    human_review_notes = Column(Text, nullable=True)

    # Audit & Timestamp Fields
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    def to_dict(self):
        return {
            "id": self.id,
            "allocation_code": self.allocation_code,
            "batch_code": self.batch_code,
            "fd_requirement_id": self.fd_requirement_id,
            "panchayat_samiti_name": self.panchayat_samiti_name,
            "gp_code": self.gp_code,
            "gp_name": self.gp_name,
            "crop_name": self.crop_name,
            "season": self.season,
            "target_year": self.target_year,
            "agricultural_area_ha": self.agricultural_area_ha,
            "active_farmers_count": self.active_farmers_count,
            
            # AI Recommendation (Preserved)
            "ai_recommended_quantity_mt": self.ai_recommended_quantity_mt,
            "ai_priority": self.ai_priority,
            "ai_suitability": self.ai_suitability,
            "ai_reasoning": self.ai_reasoning,
            "ai_confidence_score": self.ai_confidence_score,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "ai_factors": self.ai_factors or {},
            
            # Human Review (Dual Storage)
            "review_status": self.review_status,
            "human_final_quantity_mt": self.human_final_quantity_mt,
            "human_final_priority": self.human_final_priority,
            "reviewed_by": self.reviewed_by,
            "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None,
            "correction_reason": self.correction_reason,
            "human_review_notes": self.human_review_notes,
            
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

