from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Text, DateTime
from backend.database.connection import Base

class FDCropRequirement(Base):
    """
    Food Department Crop Requirement.
    AI-FIRST ARCHITECTURE:
    - Generated by Central AI/ML Engine based on cross-sector data
    - Reviewed & Adjusted by Food Department Officer
    - Approved as Final Requirement
    - Database preserves BOTH the AI-generated recommendation AND human-finalized values
    """
    __tablename__ = "fd_crop_requirements"

    id = Column(Integer, primary_key=True, index=True)
    
    # Active operational values (used in downstream allocations)
    crop_name = Column(String(50), nullable=False, index=True)
    season = Column(String(30), nullable=False) # e.g. Kharif 2026, Rabi 2026
    target_quantity_mt = Column(Float, nullable=False)
    priority = Column(String(20), default="HIGH") # NORMAL, HIGH, CRITICAL
    
    # Status progression: AI_GENERATED -> UNDER_REVIEW -> EDITED_BY_HUMAN -> APPROVED
    status = Column(String(30), default="AI_GENERATED", index=True)

    # 1. AI Recommendation Fields (PRESERVED - Never overwritten on human edits)
    ai_crop_name = Column(String(50), nullable=True)
    ai_recommended_quantity_mt = Column(Float, nullable=True)
    ai_priority = Column(String(20), nullable=True)
    ai_confidence_score = Column(Float, default=0.94)
    ai_rationale = Column(Text, nullable=True)
    ai_generated_at = Column(DateTime, default=datetime.utcnow)

    # 2. Human Final Review & Decision Fields
    human_final_quantity_mt = Column(Float, nullable=True)
    human_final_priority = Column(String(20), nullable=True)
    finalized_by = Column(String(50), nullable=True)
    finalized_at = Column(DateTime, nullable=True)
    human_review_notes = Column(Text, nullable=True)

    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "crop_name": self.crop_name,
            "season": self.season,
            "target_quantity_mt": self.target_quantity_mt,
            "priority": self.priority,
            "status": self.status,
            # AI Recommendation fields
            "ai_crop_name": self.ai_crop_name or self.crop_name,
            "ai_recommended_quantity_mt": self.ai_recommended_quantity_mt,
            "ai_priority": self.ai_priority or self.priority,
            "ai_confidence_score": self.ai_confidence_score,
            "ai_rationale": self.ai_rationale,
            "ai_generated_at": self.ai_generated_at.strftime("%Y-%m-%d %H:%M") if self.ai_generated_at else None,
            # Human Final fields
            "human_final_quantity_mt": self.human_final_quantity_mt,
            "human_final_priority": self.human_final_priority,
            "finalized_by": self.finalized_by,
            "finalized_at": self.finalized_at.strftime("%Y-%m-%d %H:%M") if self.finalized_at else None,
            "human_review_notes": self.human_review_notes,
            "notes": self.notes,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M") if self.created_at else None,
        }

class FDCrisisRecord(Base):
    __tablename__ = "fd_crisis_records"

    id = Column(Integer, primary_key=True, index=True)
    crop_name = Column(String(50), nullable=False)
    region_or_district = Column(String(100), nullable=False)
    deficit_amount_mt = Column(Float, nullable=False)
    severity = Column(String(30), default="HIGH") # MODERATE, SEVERE, ACUTE
    mitigation_strategy = Column(Text, nullable=True)
    status = Column(String(30), default="UNDER_MANAGEMENT")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "crop_name": self.crop_name,
            "region_or_district": self.region_or_district,
            "deficit_amount_mt": self.deficit_amount_mt,
            "severity": self.severity,
            "mitigation_strategy": self.mitigation_strategy,
            "status": self.status,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M") if self.created_at else None,
        }

class FDDemandProjection(Base):
    __tablename__ = "fd_demand_projections"

    id = Column(Integer, primary_key=True, index=True)
    crop_name = Column(String(50), nullable=False)
    time_period = Column(String(30), nullable=False) # e.g. FY 2026-27
    current_demand_mt = Column(Float, nullable=False)
    future_demand_mt = Column(Float, nullable=False)
    projected_growth_pct = Column(Float, nullable=True)
    remarks = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "crop_name": self.crop_name,
            "time_period": self.time_period,
            "current_demand_mt": self.current_demand_mt,
            "future_demand_mt": self.future_demand_mt,
            "projected_growth_pct": self.projected_growth_pct,
            "remarks": self.remarks,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M") if self.created_at else None,
        }

class FDWeatherData(Base):
    __tablename__ = "fd_weather_data"

    id = Column(Integer, primary_key=True, index=True)
    region = Column(String(100), nullable=False)
    season = Column(String(30), nullable=False)
    rainfall_mm = Column(Float, nullable=False)
    avg_temperature_c = Column(Float, nullable=False)
    soil_moisture_index = Column(Float, nullable=True)
    climate_alert = Column(String(100), default="NORMAL") # NORMAL, DROUGHT_RISK, FLOOD_RISK
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "region": self.region,
            "season": self.season,
            "rainfall_mm": self.rainfall_mm,
            "avg_temperature_c": self.avg_temperature_c,
            "soil_moisture_index": self.soil_moisture_index,
            "climate_alert": self.climate_alert,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M") if self.created_at else None,
        }

class FDPSAllocation(Base):
    __tablename__ = "fd_ps_allocations"

    id = Column(Integer, primary_key=True, index=True)
    panchayat_samiti_name = Column(String(100), nullable=False, index=True)
    crop_name = Column(String(50), nullable=False)
    target_quota_mt = Column(Float, nullable=False)
    
    # AI Suggestion & Human Review
    ai_suggested_quota_mt = Column(Float, nullable=True)
    ai_rationale = Column(String(255), nullable=True)
    human_final_quota_mt = Column(Float, nullable=True)
    review_status = Column(String(30), default="CONFIRMED")
    reviewed_by = Column(String(50), default="Food Directorate")
    
    status = Column(String(30), default="ASSIGNED")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "panchayat_samiti_name": self.panchayat_samiti_name,
            "crop_name": self.crop_name,
            "target_quota_mt": self.target_quota_mt,
            "ai_suggested_quota_mt": self.ai_suggested_quota_mt,
            "human_final_quota_mt": self.human_final_quota_mt,
            "ai_rationale": self.ai_rationale,
            "review_status": self.review_status,
            "status": self.status,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M") if self.created_at else None,
        }
